# Generated by Django 5.2.1 on 2025-06-04 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_owner_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='vet',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age in years', null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='bio',
            field=models.TextField(default='No bio available'),
        ),
        migrations.AddField(
            model_name='vet',
            name='experience',
            field=models.IntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='vet',
            name='specializations',
            field=models.ManyToManyField(to='clinic.specialization'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.pet'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.vet'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='owner',
            name='lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='owner',
            name='minit',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vet',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
