# Generated by Django 5.2.1 on 2025-06-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_handle_duplicates'),
        ('clinic', '0005_handle_duplicates'),
    ]

    operations = [
    ]
